# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='student',
            new_name='dojo',
        ),
    ]
